version: "3.7"
services:
  db:
    image: mysql:8.0.23
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined      
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=staging
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  redis:
    image: "redis:6.2-alpine"
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - backnet

  backend:
    build: backend
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet

volumes:
  db-data:
  redis-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
