#FROM python:3.9-slim
FROM python:3.9
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt --no-cache-dir
COPY . /app/
ENV DOCKER True
ENV PYTHONUNBUFFERED 0
#ENV FLASK_APP hello.py
#CMD flask run --host=0.0.0.0
#RUN chmod +x server.sh
#CMD server.sh 0.0.0.0 5000
RUN mkdir -p logs
CMD python3 ./serve.py --host 0.0.0.0 --port 5000
#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
