---

version: 1

disable_existing_loggers: False

formatters:
    simple:
        #format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        format: "%(asctime)s %(levelname)-9s %(name)s -: %(message)s"

    default:
        (): 'uvicorn.logging.DefaultFormatter'
        fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(message)s'
    access:
        (): 'uvicorn.logging.AccessFormatter'
        fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(client_addr)s - "%(request_line)s" %(status_code)s'

handlers:
    logfile:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        when: D
        utc: True
        filename: ./logs/info.log
        backupCount: 20

    default:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stderr
    access:
        class: logging.StreamHandler
        formatter: access
        stream: ext://sys.stdout

loggers:
    uvicorn:
        level: INFO
        handlers:
            - default
    uvicorn.error:
        level: INFO
        propagate: False        
        handlers: [default, logfile]

    uvicorn.access:
        level: INFO
        propagate: False
        handlers: [access, logfile]

root:
    level: DEBUG
    handlers: [default, logfile]